
<?php

// fetching products in category id 23
 
// Load category by category ID
$category = $block->getCategory();

$parentCategories = $category->getChildrenCategories();
$mode = 'grid';
foreach ($category->getParentCategories() as $key => $value) {
  $parentName = $value->getName();
  if ($parentName=="Industries") {
   break;
  }
  else{ ?>
    <div class="product-title-wrapper">
      <div class="pro-hedding">
          <strong role="heading" aria-level="2"><h3 style="color: #000"><?php if ($category->getName()=="Rope") echo "SHOP BY"; else echo "PRODUCT GROUPS" ?></h3></strong>
          <span class="product-title-line"></span>
          </div>
      </div>
<?php
break;
  }
}

 ?>

        <ul class="subcategory-product-group two-layout">
        <?php

foreach($parentCategories as $parentCategory){
    $children = $block->getCategoryList($parentCategory->getId());
    $product_collection ='';
     $product_collection = $block->getBestsellerProduct($parentCategory->getId());
     if(count($product_collection) == 0)
     {
          $product_collection = $parentCategory->getProductCollection()->addAttributeToSelect('*')->setPagesize(3);
     }
     if (!$parentCategory->getIsActive()) {
        continue;
     }
$child_count= 1;
?>
<li class="two-layout-item">

<a href="<?php echo $parentCategory->getUrl(); ?>">
<?php $image_url = $this->getCategoryImageUrl($parentCategory->getId());?>
<?php if($image_url == '')
{
     $image_url = $block->getNoCategoryUrl();
}
?>
<img src="<?php echo $image_url; ?>" class="two-layout-image"/>
    
<strong> <?php echo $parentCategory->getName(); ?> </strong>

</a>
    <ul>
      <?php
      //print_r($product_collection); 
      if(!$parentCategory->hasChildren()){
      $product_count = 1;
    foreach ($product_collection as $product_id=>$product_qty) :
           $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
            $product = $objectManager->get('Magento\Catalog\Model\ProductRepository')->getById($product_id);
           // echo $product_id;
            if($block->getConfigData() && $product->getShortName()){
        $productName = $product->getShortName();
      }else{
        $productName = $product->getName();
      }
        if (strlen($productName)>55) 
          $productName=substr($productName,0,55);  ?>
        <li> <a href="<?php echo $product->getProductUrl(); ?>"><?php if (strlen($productName)<55)
        echo $productName;
        else echo $productName.'...'; ?></a> </li>
        <?php
     //  echo count($product_collection);
      // echo $product_count;
    if($product_count == count($product_collection))
    {
        ?>
        <li><a href="<?php echo $parentCategory->getUrl(); ?>"><i>See all></i></a></li>
          <?php
          break;
          
    }
    
    $product_count++;
    ?>
    
<?php endforeach; 
}else{
$childcat_count = 1;
      foreach ($parentCategory->getChildrenCategories() as $childcat) : 
        if (strlen($childcat->getName())<35) 
          $childcatName=$childcat->getName();
        else $childcatName=substr($childcat->getName(),0,35); 
        ?>
        <li> <a href="<?php echo $childcat->getUrl(); ?>"><?php if (strlen($childcat->getName())<35)
        echo $childcatName;
        else echo $childcatName.'...'; ?></a> </li>
        <?php
    if($childcat_count == 3)
    {
        ?>
        <li><a href="<?php echo $parentCategory->getUrl(); ?>"><i>See all></i></a></li>
          <?php
          break;
          
    }
    
    $childcat_count++; endforeach; } ?>
    </ul>
</li>


        
        <?php 
        
             }
?>

</ul>
<script type="text/javascript">
    var category_page = 'static_block';
</script>