<?php $collection = $block->getShoppinglist(); 
?>
<!-- <div style="padding-bottom:20px; font-size:18px; font-weight:bold;">Shopping List</div> -->
<form class="form form-login" action="<?php echo $block->getUrl('shoppinglist/index/add');?>" method="post" id="shoppinglist-form">
    <?php echo $block->getBlockHtml('formkey'); ?>

    <div class="field note" style="padding-bottom:20px;">Enter a name for your new shopping list and then click submit.</div>
    <div class="field required" style="padding-bottom:10px;">
        <span style="padding-right:35px;">Create a new list:</span>
        <input name="shoppinglist_name" value="" id="shoppinglist_name" type="text" class="input-text" title="<?php /* @escapeNotVerified */ echo __('Shoppinglist Name') ?>" data-validate="{required:true}" style="width:200px;margin-right: 2px">
        <button type="submit" class="action login primary" name="send" id="send2"><span>Submit</span></button>
    </div>
</form>
<?php if(count($collection)) { ?>
    <form name="shoppinglist-groupname" id="shoppinglist-groupname" method="post" action="<?php echo $block->getUrl('shoppinglist/index/index');?>">
        <div class="field required" style="padding-bottom:20px;">
            <span style="padding-right:5px;">Custom Shopping list:</span>
            <select name="shoppinglist" id="shoppinglist" title="<?php echo __('Shoppinglist') ?>" data-validate="{required:true}" style="width:200px;margin-right: 1px">
                <?php 
                if(isset($_REQUEST['shoppinglist']))
                    $item_id = $_REQUEST['shoppinglist'];
                else if($block->getShoppinglistId())
                    $item_id = $block->getShoppinglistId();
                else
                    $item_id = 0;

                for($i=0; $i<count($collection); $i++ )
                {
                    if(!$item_id)
                        $item_id = $collection[$i]['id'];
                    ?>
                    <option value="<?php echo $collection[$i]['id'];?>" <?php if($collection[$i]['id']==$item_id) echo "selected"; ?>><?php echo $collection[$i]['list_name'];?></option>
                <?php } ?>
            </select>
            <button type="submit" class="action login primary" name="send" id="send2"><span>Submit</span></button>
        </div>
    </form>
<?php } ?>
<?php if(count($collection)) { 
    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    ?>

    <form class="form form-login" action="<?php echo $block->getUrl('shoppinglist/index/updatelist');?>" method="post" id="shoppinglist-form-add" >
        <?php echo $block->getBlockHtml('formkey'); ?>

        <?php $productCollection = $block->getShoppinglistProduct($item_id); ?>

        <table id="shoping_item" class="product_dckaptable">
            <tbody>
                <tr class="prouct-tabel">
                    <th style=" width: 90px;">Item Code</th>
                    <th style=" width: 50%;">Description</th>
                    <th>Quantity</th>
                    <th>Add to Cart</th>
                    <th><a class="delete dckap-sprite"></a></th>
                </tr>   

                <?php 
                if(count($productCollection) > 0){
                    foreach($productCollection as $key=>$product) {
                        $product_obj = $objectManager->get('Magento\Catalog\Model\Product')->load($product['item_id']);
                        ?>

                        <tr>
                            <td><?php echo $product_obj->getSku(); ?></td>
                            <td><?php echo $product_obj->getName(); ?></td>               

                            <td>  
                                <input type="text" name="qty" style="width:40px;" value="<?php echo $product['qty']; ?>" />
                                <input type="hidden" name="pid" id="pid" value="<?php echo $product['item_id'];?>" />
                                <input type="hidden" class="old_qty" value="<?php echo $product['qty']; ?>" />
                            </td>
                            <td><input type="checkbox" name="bulk[]" style="width:13px;cursor:pointer" checked="checked" value="<?php echo $product['item_id'];?>" /></td>
                            <td><a title="Delete Row" href="javascript:void(0);" class="delete-ico dckap-sprite"></a><input type="hidden" value="<?php echo $product['shopping_list_item_id'];?>" ></td>
                        </tr>  

                <?php } }else{ ?>
                    <tr id="error"><td colspan="7">There is no item for the list.</td></tr>
                <?php } ?>
            </tbody>
        </table>
        <div style='padding-bottom:10px;' id='newitem'><span class="shopping_add_list"><input name='product_name' value='' id='product_name'  type='text' class='input-text' title=''/><input type='hidden' name='product_id' id='product_id' /><img width="25" height="25" src='<?php echo $block->getViewFileUrl('Dckap_Quickorder::images/loading.gif');?>' style='display:none;' class='item_loader'>  </span></div>

        <button title="Add New Item to List" type="button" class="action login primary" name="send" id="updatelist"><span>Add New Item to List</span></button></td></tr>
        <input type="hidden" name="removed_item" id="removed_item"/>
        <input type="hidden" name="shoppinglist_id" id="shoppinglist_id" value="<?php echo $item_id;?>" />
        
        <div class="decider-list" align="right"><button title="Delete List" type="submit" class="action login primary" name="send" id="deletelist" style="margin-right:20px;"><span>Delete List</span></button><!-- <button type="submit" class="action login primary" name="send" id="updatelist" style="margin-right:20px;"><span>Update List</span></button> --><button title="Add List to Cart" type="submit" class="action login primary" name="send" id="addtocart"><span>Add List to Cart</span></button></div>
    </form>

<?php } ?>

<script>
require(['jquery','mage/mage'], function($){

    var dataForm = $('#shoppinglist-form');
    var ignore = null;

    dataForm.mage('validation', {});

    $('input[name="qty"]').on("blur", function() {

        jQuery.ajax({
            dataType: 'text',
            type: 'post',
            contentType: 'application/x-www-form-urlencoded',
            data: {'pid' : $(this).next().val(), 'slistid' : $('#shoppinglist_id').val(), 'qty' : $(this).val()},
            url:'<?php echo $block->getUrl('shoppinglist/index/updateqty');?>',
            crossDomain:false,
            success:function(data, textStatus, jQxhr){
            }
        });
    });

    $("#updatelist").click(function() {
        if($('#product_name').val()==""){
            alert("Please add any one item to add in the list");
            return false;
        }

        if($('#product_id').val()){
            $('span .item_loader').show(function(){
                jQuery.ajax({
                    dataType: 'text',
                    type: 'post',
                    contentType: 'application/x-www-form-urlencoded',
                    data: {'pid' : $('#product_id').val(), 'slistid' : $('#shoppinglist_id').val()},
                    url:'<?php echo $block->getUrl('shoppinglist/index/updatelist');?>',
                    crossDomain:false,
                    success:function(data, textStatus, jQxhr){
                        if(data){
                            $("#error").remove();
                            $('#product_name').val('');
                            $('#shoping_item tr:last').after(data);     
                        }else{
                            alert("The product you have added already available in the list.");
                            $('#product_name').val('');
                        }
                        $('span .item_loader').hide(); 
                    }
                });
            });
        }else{
            alert("Please add valid item to add in the list");
            return false;
        }
    });

    $(".delete-ico").on('click', function() {
        $(this).parent().parent().remove();
        delid = $(this).next().val();

        jQuery.ajax({
            dataType: 'text',
            type: 'post',
            contentType: 'application/x-www-form-urlencoded',
            data: {'shoppinglist_id' : delid},
            url:'<?php echo $block->getUrl('shoppinglist/index/deletelist');?>',
            crossDomain:false,
            success:function(data, textStatus, jQxhr){
            }
        });
    })

    $("#addtocart").click(function() {
        if($('input[name="bulk[]"]:checked').length==0){
            alert("Please choose any one of the items from list");
            return false;
        }
        $("#shoppinglist-form-add").attr("action", "<?php echo $block->getUrl('shoppinglist/index/addproduct');?>");
    });

    $("#deletelist").click(function() {
        if(confirm("Are you sure you want to delete shoppinglist")) {
            $("#shoppinglist-form-add").attr("action", "<?php echo $block->getUrl('shoppinglist/index/deletelistitem');?>");
            return true;
        } else {
            return false;
        }
    });

    $(document).ready(function () {
        enableAutocompletel(jQuery('#newitem')); 
    });

    function enableAutocompletel(pSelector) {    
        var cache = {};
        var ac_min_chars = 3;
        jQuery('#shoppinglist-form-add').find('input[name="product_name"]').autocomplete({
            minLength : ac_min_chars,
            delay:500,
            html: true,        
            source: function (request, response) {
                var searchKeyword = request.term;
                if(jQuery.trim(searchKeyword) != '') {
                    if ( searchKeyword in cache ) {
                        response(cache[searchKeyword]);
                        return;
                    }
                    var ac_item = this.element;
                    ac_item.siblings('.item_loader').show(function(){
                        jQuery.ajax({
                            cache:true,
                            dataType:'json',
                            method: 'POST',
                            /*async: false,*/
                            url:'<?php echo $block->getUrl('shoppinglist/index/getproduct');?>',
                            data:{query:searchKeyword},
                            crossDomain:false,
                            success:function(datasuggestions){
                                /*if(jQuery.trim(datasuggestions) == '') {
                                datasuggestions = [{"label":"No Matches Found","title":"No Matches Found","value":"no-matches"}];
                                }*/
                                cache[searchKeyword] = datasuggestions;
                                response(datasuggestions);  
                                ac_item.siblings('.item_loader').hide();  
                            }
                        });
                    });

                }                              
            },
            /*search: function( event, ui ) {
            jQuery(this).siblings('.item_loader').show();            
            },
            response: function( event, ui ) {
            jQuery(this).siblings('.item_loader').hide();
            },*/
            focus: function( event, ui ) {
                if(jQuery.trim(ui.item.value) != 'no-matches') {          
                    var itemTitle = jQuery('<textarea />').html(ui.item.label).text();
                    jQuery(this).val(itemTitle);
                }    
                return false;
            },
            select: function( event, ui ) {
                if(ui.item.value == 'no-matches')
                return false;

                var ac_element = jQuery(this);
                // ac_element.siblings('.item_loader').show();            
                var elmParent = jQuery(this).parents('tr');
                var parentTd = jQuery(this).parents('td');
                //jQuery('#quickorder_message_wrap,#quickorder_error_wrap').hide();
                var prodId = ui.item.value;
                var itemTitle = jQuery('<textarea />').html(ui.item.label).text();
                jQuery(this).val(itemTitle);
                jQuery(this).siblings('input:hidden').val( ui.item.productid );            
                //elmParent.find('.txt-sku').html(ui.item.sku);
                //elmParent.find('.pqty').html(ui.item.price);
                //elmParent.find('.txt-qty').val(1);
                //parentTd.find('.confBlock').remove();

                //elmParent.addClass('simple');
                // elmParent.find('.txt-qty').show();
                // ac_element.siblings('.item_loader').hide();
                return false;
            }/*,
            messages: {
            noResults: '',
            results: function() {}
            }*/
        }).click(function(){
            jQuery(this).autocomplete('search');        
        });  
        return false;
    }
});
</script>
<script type="text/javascript">
require(['jquery'], function(jQuery){
    jQuery(document).ready(function () {
        window.sdisplayBoxIndex = -1;
        var Navigateshoppinglist = function (diff) { 

            sdisplayBoxIndex += diff;
            var oBoxCollection = jQuery("#ui-id-1 li");
            if (sdisplayBoxIndex >= oBoxCollection.length) {
                sdisplayBoxIndex = 0;
            }
            if (sdisplayBoxIndex < 0) {
                sdisplayBoxIndex = oBoxCollection.length - 1;
            }
            var cssClass = "display_box_hover";
            oBoxCollection.removeClass(cssClass).eq(sdisplayBoxIndex).addClass(cssClass);
            //jQuery("li.display_box_hover a").focus();
        }

        jQuery("#product_name").on("keydown", function(e){
            switch(e.which) {
                case 38: // up
                    Navigateshoppinglist(-1);
                break;
                case 40: // down
                    Navigateshoppinglist(1);
                break;
                default: return; // exit this handler for other keys
            }
            e.preventDefault(); // prevent the default action (scroll / move caret)
        });
    });
});
</script>