<?php
$customerId = $block->getCustomerLoggedin();
// echo $block->getCustomerSession()->getCustomer()->getName();
?>
<div class="purchase_reports">
    <p>Select the reports you would like to review</p>
    <div class="loading-mask" data-role="loader" style="display: none;"><div class="loader"><img alt="Loading..." src="<?php echo $block->getViewFileUrl('Dckap_PurchaseReport::images/loader-2.gif'); ?>"><p>Please wait...</p></div></div>
    <table class="product_temptable">
        <tbody>
            <tr>
                <th>Report Type</th>
                <th>Cycle</th>
                <th></th>
                <th></th>
            </tr>
            <tr>
                <td>Purchase by Item Number</td>
                <td><select style="color:#000">
                <option>Rolling year</option>
                <option>Year to Date</option>
                </select></td>
                <td><a href="javascript:void(0)" class="pdf_report" id="item_number">Download PDF</a></td>
                <td><a href="javascript:void(0)" class="email_report" id="email_product_item" >Email reports now</a></td>
            </tr>
            <tr>
                <td>Purchase by Product Category</td>
                <td><select style="color:#000">
                <option>Rolling year</option>
                <option>Year to Date</option>
                </select></td>
                <td><a href="javascript:void(0)" class="pdf_report" id="product_category">Download PDF</a></td>
               <td><a href="javascript:void(0)" class="email_report" id="email_product_category" >Email reports now</a></td>
            </tr>
            <tr>
                <td>Purchase by Location</td>
                <td><select style="color:#000">
                <option>Rolling year</option>
                <option>Year to Date</option>
                </select></td>
                <td><a href="javascript:void(0)" class="pdf_report" id="location">Download PDF</a></td>
                <td><a href="javascript:void(0)" class="email_report" id="email_location">Email reports now</a></td>
            </tr>
        </tbody>
    </table> 
</div>
<script type="text/javascript">
    require(['jquery'], function($) {
        $( document ).ready(function() {

            var Base_url = "<?php echo $this->getBaseUrl(); ?>";
            var d = new Date();
            var dd = d.getDate();
            if(dd<10){
                dd = '0'+dd;
            }
            //minus 1 day
            var day1 = new Date();
            var day_1 = day1.setDate(d.getDate() -1);
            var day_1 = day1.getDate();
            if(day_1<10){
                day_1 = '0'+day_1;
            }
            //minus 2 day
            var day2 = new Date();
            var day_2 = day2.setDate(d.getDate() -2);
            var day_2 = day2.getDate();
            if(day_2<10){
                day_2 = '0'+day_2;
            }
            var mm = (d.getMonth()+1)
            if(mm<10){
                mm = '0'+mm;
            }
            var today = mm +'/'+dd+'/'+d.getFullYear().toString().substr(2,2);
            var currentYear = '01/01/'+d.getFullYear().toString().substr(2,2);
            var yearToDate = '('+currentYear+'-'+today+')';
            var rollingyearcurdate = mm +'/'+day_2+'/'+d.getFullYear().toString().substr(2,2);
            var previousYear = mm +'/'+day_1+'/'+ (d.getFullYear()-1).toString().substr(2,2);
            var rollinYear = '('+previousYear+'-'+rollingyearcurdate+')';

            function getDataUri(url, cb)
            {
                var image = new Image();
                image.setAttribute('crossOrigin', 'anonymous'); //getting images from external domain

                image.onload = function () {
                    var canvas = document.createElement('canvas');
                    canvas.width = this.naturalWidth;
                    canvas.height = this.naturalHeight; 

                    //next three lines for white background in case png has a transparent background
                    var ctx = canvas.getContext('2d');
                    ctx.fillStyle = '#fff';  /// set white fill style
                    ctx.fillRect(0, 0, canvas.width, canvas.height);

                    canvas.getContext('2d').drawImage(this, 0, 0);

                    cb(canvas.toDataURL('image/jpeg'));
                };
                image.src = url;
            }

            // Usage
            var headerImgData

            $( "#email_location").on( "click", function() {
                $('.loading-mask').show();
                var attachment_type= '';
                var req_report = $(this).attr('id');
                var roll_year = $(this).parent().prev('td').prev('td').children().find(":selected").text();
                $("input[value='email_location']").each(function()
                {
                    if($(this).is(":checked"))
                    {
                        attachment_type= $(this).attr('data-role');
                    }
                });
                getDataUri(Base_url +'pub/media/logo/default/purchasereport-min.png', function(dataUri) {
                    headerImgData =dataUri;
                });
                if(roll_year == 'Rolling year'){
                    var purchaseDate = rollinYear;
                }else{
                    var purchaseDate = yearToDate;
                }
                $.ajax({
                    url:Base_url +"purchase/report/purchasebylocation",
                    type: 'post',
                    dataType: "json",
                    contentType: 'application/x-www-form-urlencoded',
                    data: {'req_report' :req_report,'roll_year':roll_year},
                    success: function(response ){
                        var inside_data = [];
                        var j = 0;
                        for(var i=0;i<response.length;i++)
                        {
                            if(i!=0)
                            {
                                inside_data[j] = response[i];
                                j++;
                            }
                        }
                        var columns = response[0];
                        var doc = new jsPDF('l', 'pt','a3');
                        var header = function (data) {
                        doc.setFontSize(20);
                        doc.setTextColor(40);
                        doc.setFontStyle('normal');
                        //  doc.text("Continental Western Corporat", 'JPEG', data.settings.margin.left, 40, 629, 67);
                        };

                        var options = {
                            beforePageContent: header,
                            margin: {top: 140},
                            startY: 170
                        };
                        doc.setFontSize(15);
                        doc.text("Spend by Location "+purchaseDate, 40 , 135);
                        doc.setFontSize(12);
                        doc.setTextColor(100); 

                        var text = "Customer Account# : <?php echo $customerId; ?>"
                        doc.text(text, 40, 160);

                        var cols = columns;
                        //cols.splice(0, 2);
                        doc.autoTable(cols, inside_data,options );

                        var pdf =doc.output(); //returns raw body of resulting PDF returned as a string as per the plugin documentation.
                        var data = new FormData();
                        data.append("data" , pdf);
                        var xhr = new XMLHttpRequest();
                        xhr.open( 'post', Base_url+'purchase/report/emailreport', true ); //Post to php Script to save to server
                        xhr.send(data);

                        xhr.onreadystatechange = function() {
                            if(xhr.readyState == 4) {
                                alert( xhr.responseText);
                                $('.loading-mask').hide();
                            }
                        }
                    },
                    error: function( errorThrown ){
                        console.log( errorThrown );
                    }
                });
            });

            $( "#email_product_item").on( "click", function() {
                $('.loading-mask').show();
                var attachment_type= '';
                var req_report = $(this).attr('id');
                var roll_year = $(this).parent().prev('td').prev('td').children().find(":selected").text();
                console.log(roll_year);
                $("input[value='email_location']").each(function()
                {
                    if($(this).is(":checked"))
                    {
                        attachment_type= $(this).attr('data-role');
                    }
                });
                getDataUri(Base_url +'pub/media/logo/default/purchasereport-min.png', function(dataUri) {
                    headerImgData =dataUri;
                });
                if(roll_year == 'Rolling year'){
                    var purchaseDate = rollinYear;
                }else{
                    var purchaseDate = yearToDate;
                }
                $.ajax({
                    url:Base_url +"purchase/report/purchasebyitemnumber",
                    type: 'post',
                    dataType: "json",
                    contentType: 'application/x-www-form-urlencoded',
                    data: {'req_report' :req_report,'roll_year':roll_year},
                    success: function(response ){
                        var columns = ['Item #',"Item Description", "Total Amount","Total Quantity Ordered"];
                        //	console.log(response); return;
                        var inside_data = response;

                        var doc = new jsPDF('l', 'pt','a3');
                        var header = function (data) {
                            doc.setFontSize(20);
                            doc.setTextColor(40);
                            doc.setFontStyle('normal');     
                        };

                        var options = {
                            beforePageContent: header,
                            margin: {top: 140},
                            startY: 170
                        };
                        doc.setFontSize(15);
                        doc.text("Spend by Item Number "+purchaseDate, 40 , 135);
                        doc.setFontSize(12);
                        doc.setTextColor(100);
                        //var text = doc.splitTextToSize(('Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus eu urna auctor, ultrices nisl eget, tempus nulla. Vestibulum et tellus vitae dui dictum gravida id ac mauris. Nulla ut turpis nec quam malesuada feugiat. Nullam auctor mi eu mollis condimentum. Pellentesque maximus eros a nunc commodo pellentesque. Ut ultricies, sapien et condimentum hendrerit, felis leo lobortis tellus, sit amet sodales neque dui at elit. Praesent in molestie libero. Aenean malesuada purus ut sapien rhoncus mattis.') + '.', doc.internal.pageSize.width - 80, {});
                        var text = "Customer Account#: <?php echo $customerId; ?>"
                        doc.text(text, 40, 160);

                        var cols = columns;
                        //cols.splice(0, 2);
                        doc.autoTable(cols, inside_data,options );



                        var pdf =doc.output(); //returns raw body of resulting PDF returned as a string as per the plugin documentation.
                        var data = new FormData();
                        data.append("data" , pdf);
                        var xhr = new XMLHttpRequest();
                        xhr.open( 'post',Base_url + 'purchase/report/emailreport', true ); //Post to php Script to save to server
                        xhr.send(data);
                        xhr.onreadystatechange = function() {
                            if(xhr.readyState == 4) {
                                alert( xhr.responseText);
                                $('.loading-mask').hide();
                            }
                    }
                    //doc.save('table.pdf');

                    },
                    error: function( errorThrown ){
                        console.log( errorThrown );
                    }
                });
            });

            $( "#email_product_category").on( "click", function() {
                $('.loading-mask').show();
                var attachment_type= '';
                var req_report = $(this).attr('id');
                var roll_year = $(this).parent().prev('td').prev('td').children().find(":selected").text();
                $("input[value='email_product_category']").each(function()
                {
                    if($(this).is(":checked"))
                    {
                        attachment_type= $(this).attr('data-role');
                    }
                });
                getDataUri(Base_url +'pub/media/logo/default/purchasereport-min.png', function(dataUri) {
                headerImgData =dataUri;
                });
                if(roll_year == 'Rolling year'){
                    var purchaseDate = rollinYear;
                }else{
                    var purchaseDate = yearToDate;
                }
                $.ajax({
                    url:Base_url +"purchase/report/purchasebyproductcategory",
                    type: 'post',
                    dataType: "json",
                    contentType: 'application/x-www-form-urlencoded',
                    data: {'req_report' :req_report,'roll_year':roll_year},
                    success: function(response ){
                        var inside_data = [];
                        var j = 0;
                        for(var i=0;i<response.length;i++)
                        {
                            if(i!=0)
                            {
                                inside_data[j] = response[i];
                                j++;
                            }
                        }       

                        var columns = response[0];
                        var doc = new jsPDF('l', 'pt','a3');
                        var header = function (data) {
                            doc.setFontSize(20);
                            doc.setTextColor(40);
                            doc.setFontStyle('normal');
                            //  doc.text("Continental Western Corporat", 'JPEG', data.settings.margin.left, 40, 629, 67);

                        };

                        var options = {
                            beforePageContent: header,
                            margin: {top: 140},
                            startY: 170
                        };
                        doc.setFontSize(15);
                        doc.text("Spend by Product Category "+purchaseDate, 40 , 135);
                        doc.setFontSize(12);
                        doc.setTextColor(100); 

                        var text = "Customer Account#: <?php echo $customerId; ?>"
                        doc.text(text, 40, 160);

                        var cols = columns;
                        //cols.splice(0, 2);
                        doc.autoTable(cols, inside_data,options );

                        var pdf =doc.output(); //returns raw body of resulting PDF returned as a string as per the plugin documentation.
                        var data = new FormData();
                        data.append("data" , pdf);
                        var xhr = new XMLHttpRequest();
                        xhr.open( 'post', Base_url +'purchase/report/emailreport', true ); //Post to php Script to save to server
                        xhr.send(data);
                        xhr.onreadystatechange = function() {
                            if(xhr.readyState == 4) {
                                alert( xhr.responseText);
                                $('.loading-mask').hide();
                            }
                        }
                        //doc.save('table.pdf');

                    },
                    error: function( errorThrown ){
                        console.log( errorThrown );
                    }
                });
            });


            $( "#location").on( "click", function() {
                var req_report = $(this).attr('id');
                var roll_year = $(this).parent().prev('td').children().find(":selected").text();
                getDataUri(Base_url +'pub/media/logo/default/purchasereport-min.png', function(dataUri) {
                    headerImgData =dataUri;
                });
                if(roll_year == 'Rolling year'){
                    var purchaseDate = rollinYear;
                }else{
                    var purchaseDate = yearToDate;
                }
                $.ajax({
                    url:Base_url +"purchase/report/purchasebylocation",
                    type: 'post',
                    dataType: "json",
                    contentType: 'application/x-www-form-urlencoded',
                    data: {'req_report' :req_report,'roll_year':roll_year},
                    success: function(response ){
                        var inside_data = [];
                        var j = 0;
                        for(var i=0;i<response.length;i++)
                        {
                            if(i!=0)
                            {
                                inside_data[j] = response[i];
                                j++;
                            }
                        }       

                        var columns = response[0];
                        var doc = new jsPDF('l', 'pt','a3');
                        var header = function (data) {
                            doc.setFontSize(20);
                            doc.setTextColor(40);
                            doc.setFontStyle('normal');
                            doc.addImage(headerImgData, 'JPEG', data.settings.margin.left, 40, 200, 80);

                        };

                        var options = {
                            beforePageContent: header,
                            margin: {top: 140},
                            startY: 170
                        };
                        doc.setFontSize(15);
                        doc.text("Spend by Location "+purchaseDate, 40 , 135);
                        doc.setFontSize(12);
                        doc.setTextColor(100);
                        //var text = doc.splitTextToSize(('Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus eu urna auctor, ultrices nisl eget, tempus nulla. Vestibulum et tellus vitae dui dictum gravida id ac mauris. Nulla ut turpis nec quam malesuada feugiat. Nullam auctor mi eu mollis condimentum. Pellentesque maximus eros a nunc commodo pellentesque. Ut ultricies, sapien et condimentum hendrerit, felis leo lobortis tellus, sit amet sodales neque dui at elit. Praesent in molestie libero. Aenean malesuada purus ut sapien rhoncus mattis.') + '.', doc.internal.pageSize.width - 80, {});
                        var text = "Customer Account# : <?php echo $customerId; ?>"
                        doc.text(text, 40, 160);

                        var cols = columns;
                        //cols.splice(0, 2);
                        doc.autoTable(cols, inside_data,options );
                        // doc.output('dataurlnewwindow'); 
                        doc.save('Purchase_Report_By_Location.pdf'); 

                    },
                    error: function( errorThrown ){
                        console.log( errorThrown );
                    }
                });
            });

            $( "#product_category").on( "click", function() {
                var req_report = $(this).attr('id');
                var roll_year = $(this).parent().prev('td').children().find(":selected").text();
                getDataUri(Base_url +'pub/media/logo/default/purchasereport-min.png', function(dataUri) {
                    headerImgData =dataUri;
                });


                if(roll_year == 'Rolling year'){
                    var purchaseDate = rollinYear;
                }else{
                    var purchaseDate = yearToDate;
                }
                $.ajax({
                    url:Base_url +"purchase/report/purchasebyproductcategory",
                    type: 'post',
                    dataType: "json",
                    contentType: 'application/x-www-form-urlencoded',
                    data: {'req_report' :req_report,'roll_year':roll_year},
                    success: function(response ){
                        var inside_data = [];
                        var j = 0;
                        for(var i=0;i<response.length;i++)
                        {
                            if(i!=0)
                            {
                                inside_data[j] = response[i];
                                j++;
                            }
                        }      

                        var columns = response[0];;
                        var doc = new jsPDF('l', 'pt','a3');
                        var header = function (data) {
                            doc.setFontSize(20);
                            doc.setTextColor(40);
                            doc.setFontStyle('normal');
                            doc.addImage(headerImgData, 'JPEG', data.settings.margin.left, 40, 200, 80);
                        };

                        var options = {
                            beforePageContent: header,
                            margin: {top: 140},
                            startY: 170
                        };
                        doc.setFontSize(15);
                        doc.text("Spend by Product Category "+purchaseDate, 40 , 135);
                        doc.setFontSize(12);
                        doc.setTextColor(100);
                        //var text = doc.splitTextToSize(('Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus eu urna auctor, ultrices nisl eget, tempus nulla. Vestibulum et tellus vitae dui dictum gravida id ac mauris. Nulla ut turpis nec quam malesuada feugiat. Nullam auctor mi eu mollis condimentum. Pellentesque maximus eros a nunc commodo pellentesque. Ut ultricies, sapien et condimentum hendrerit, felis leo lobortis tellus, sit amet sodales neque dui at elit. Praesent in molestie libero. Aenean malesuada purus ut sapien rhoncus mattis.') + '.', doc.internal.pageSize.width - 80, {});
                        var text = "Customer Account# : <?php echo $customerId; ?>"
                        doc.text(text, 40, 160);

                        var cols = columns;
                        //cols.splice(0, 2);
                        doc.autoTable(cols, inside_data,options );
                        doc.save('Purchase_Report_By_Category.pdf'); 

                    },
                    error: function( errorThrown ){
                        console.log( errorThrown );
                    }
                });
            });



            $( "#item_number").on( "click", function() {
                var req_report = $(this).attr('id');
                var roll_year = $(this).parent().prev('td').children().find(":selected").text();
                getDataUri(Base_url +'pub/media/logo/default/purchasereport-min.png', function(dataUri) {
                    headerImgData =dataUri;
                });
                if(roll_year == 'Rolling year'){
                    var purchaseDate = rollinYear;
                }else{
                    var purchaseDate = yearToDate;
                }
                $.ajax({
                    url:Base_url +"purchase/report/purchasebyitemnumber",
                    type: 'post',
                    dataType: "json",
                    contentType: 'application/x-www-form-urlencoded',
                    data: {'req_report' :req_report,'roll_year':roll_year},
                    success: function(response ){

                        var columns = ['Item #',"Item Description", "Total Amount","Total Quantity Ordered"];
                        //	console.log(response); return;
                        var inside_data = response;

                        var doc = new jsPDF('l', 'pt','a3');
                        var header = function (data) {
                            doc.setFontSize(20);
                            doc.setTextColor(40);
                            doc.setFontStyle('normal');
                            doc.addImage(headerImgData, 'JPEG', data.settings.margin.left, 40, 200, 80);

                        };

                        var options = {
                            beforePageContent: header,
                            margin: {top: 140},
                            startY: 170
                        };
                        doc.setFontSize(15);
                        doc.text("Spend by Item Number "+purchaseDate, 40 , 135);
                        doc.setFontSize(12);
                        doc.setTextColor(100);
                        //var text = doc.splitTextToSize(('Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus eu urna auctor, ultrices nisl eget, tempus nulla. Vestibulum et tellus vitae dui dictum gravida id ac mauris. Nulla ut turpis nec quam malesuada feugiat. Nullam auctor mi eu mollis condimentum. Pellentesque maximus eros a nunc commodo pellentesque. Ut ultricies, sapien et condimentum hendrerit, felis leo lobortis tellus, sit amet sodales neque dui at elit. Praesent in molestie libero. Aenean malesuada purus ut sapien rhoncus mattis.') + '.', doc.internal.pageSize.width - 80, {});
                        var text = "Customer Account# : <?php echo $customerId; ?>"
                        doc.text(text, 40, 160);

                        var cols = columns;
                        //cols.splice(0, 2);
                        doc.autoTable(cols, inside_data,options );
                        //  doc.output('dataurlnewwindow'); 
                        doc.save('Purchase_Report_By_Item.pdf'); 

                    },
                    error: function( errorThrown ){
                    console.log( errorThrown );
                    }
                });
            });

        });
    });
</script>