<?php
/**
* Copyright © 2016 Magento. All rights reserved.
* See COPYING.txt for license details.
*/

// @codingStandardsIgnoreFile

?>
<?php
/**
* Create account form template
*
* @var $block \Magento\Customer\Block\Form\Register
*/
?>
<?php echo $block->getChildHtml('form_fields_before')?>
<?php /* Extensions placeholder */ ?>
<?php echo $block->getChildHtml('customer.form.register.extra')?>
<?php 
    $categoryId = 3;
    $_objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    $category = $_objectManager->create('Magento\Catalog\Model\Category')->load($categoryId);
    $childCategories=$category->getChildrenCategories();
?>
<form class="form create account form-create-account" action="<?php /* @escapeNotVerified */ echo $block->getPostActionUrl() ?>" method="post" id="form-validate" enctype="multipart/form-data" autocomplete="off">
    <fieldset class="fieldset create info">
        <legend class="legend"><span><?php /* @escapeNotVerified */ echo __('Personal Information') ?></span></legend><br>
        <input type="hidden" name="success_url" value="<?php /* @escapeNotVerified */ echo $block->getSuccessUrl() ?>">
        <input type="hidden" name="error_url" value="<?php /* @escapeNotVerified */ echo $block->getErrorUrl() ?>">
        <?php echo $block->getLayout()->createBlock('Dckap\CustomerRegistration\Block\Widget\Fname')->setObject($block->getFormData())->setForceUseCustomerAttributes(true)->toHtml() ?>
        <div class="field">
            <div class="control">
                <input type="text" name="title" placeholder="Title" id="title" value="<?php echo $block->escapeHtml($block->getFormData()->getTitle()) ?>" title="<?php /* @escapeNotVerified */ echo __('Title') ?>" class="input-text" >
            </div>
        </div>
        <div class="field company">
            <div class="control">
                <input type="text" name="company" placeholder="Company" id="company" value="<?php echo $block->escapeHtml($block->getFormData()->getCompany()) ?>" title="<?php /* @escapeNotVerified */ echo __('Company') ?>" class="input-text <?php /* @escapeNotVerified */ echo $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('company') ?>">
            </div>
        </div>
        <div class="field ">
            <div class="control">
                <select id="industry" name="industry"  title="<?php /* @escapeNotVerified */ echo __('Industry') ?>">
                    <option value=""><?php /* @escapeNotVerified */ echo __('Please Select Industry') ?></option>
                    <?php foreach ($childCategories as $key => $value) { if($value->getIsActive()){ ?>
                    <option value="<?php  echo $value->getName(); ?>" <?php if ($block->escapeHtml($block->getFormData()->getIndustry())==$value->getName()) {
                        echo "selected='selected'";
                    }?>><?php  echo $value->getName(); ?></option>
                    <?php }else continue; } ?>
                </select>
            </div>
        </div> 
        <div class="field ">
            <div class="control">
                <input type="email" name="email" placeholder="Email*" id="email_address" value="<?php echo $block->escapeHtml($block->getFormData()->getEmail()) ?>" title="<?php /* @escapeNotVerified */ echo __('Email') ?>" class="input-text" data-validate="{required:true,'validate-email':true}">
            </div>
        </div>
        <div class="field password" data-mage-init='{"passwordStrengthIndicator": {}}'>
            <div class="control">
                <input type="password" placeholder="Password*" id="password" name="password" title="<?php /* @escapeNotVerified */ echo __('Password') ?>" class="input-text" data-password-min-length="<?php echo $block->escapeHtml($block->getMinimumPasswordLength()) ?>"
                data-password-min-character-sets="<?php echo $block->escapeHtml($block->getRequiredCharacterClassesNumber()) ?>" data-validate="{required:true, 'validate-customer-password':true}" autocomplete="off">
            </div>
        </div>
        <div class="field confirmation">
            <div class="control">
                <input type="password" placeholder="Confirm Password*" name="password_confirmation" title="<?php /* @escapeNotVerified */ echo __('Confirm Password') ?>" id="password-confirmation" class="input-text" data-validate="{required:true, equalTo:'#password'}" autocomplete="off">
            </div>
        </div>
        <input type="checkbox" id="avail_credit" class="facebox" name="avail credit" /><span>Apply for Credit</span>
        <div id="fb-wrap">
            <div class="fb">
                <div class="fb-head">
                    <h1>Credit Application</h1>
                </div>
                <div class="fb-body"> 
                    <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('credit_block')->toHtml();?>
                </div>
                <a id="close" >&times;</a>
            </div>
        </div>
        <div id="filename"></div>
        <?php if ($block->isNewsletterEnabled()): ?>
            <div class="field choice newsletter">
                <input type="checkbox" name="is_subscribed" title="<?php /* @escapeNotVerified */ echo __('Sign Up for Newsletter') ?>" value="1" id="is_subscribed"<?php if ($block->getFormData()->getIsSubscribed()): ?> checked="checked"<?php endif; ?> class="checkbox">
                <label for="is_subscribed" class="label"><span><?php /* @escapeNotVerified */ echo __('Sign Up for Newsletter') ?></span></label>
            </div>
            <?php /* Extensions placeholder */ ?>
            <?php echo $block->getChildHtml('customer.form.register.newsletter')?>
        <?php endif ?>

        <?php $_dob = $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Dob') ?>
        <?php if ($_dob->isEnabled()): ?>
            <?php echo $_dob->setDate($block->getFormData()->getDob())->toHtml() ?>
        <?php endif ?>

        <?php $_taxvat = $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Taxvat') ?>
        <?php if ($_taxvat->isEnabled()): ?>
            <?php echo $_taxvat->setTaxvat($block->getFormData()->getTaxvat())->toHtml() ?>
        <?php endif ?>

        <?php $_gender = $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Gender') ?>
        <?php if ($_gender->isEnabled()): ?>
            <?php echo $_gender->setGender($block->getFormData()->getGender())->toHtml() ?>
        <?php endif ?>
    </fieldset>
    <?php $this->setShowAddressFields(true); ?>
    <fieldset class="fieldset address">
        <legend class="legend"><span><?php /* @escapeNotVerified */ echo __('Address Information') ?></span></legend><br>
        <input type="hidden" name="create_address" value="1" />
        <?php $_streetValidationClass = $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('street'); ?>

        <div class="field street">
            <div class="control">
                <input type="text" name="street[]" placeholder="Street Address*" value="<?php echo $block->escapeHtml($block->getFormData()->getStreet(0)) ?>" title="<?php /* @escapeNotVerified */ echo __('Street Address') ?>" id="street_1" class="input-text <?php /* @escapeNotVerified */ echo $_streetValidationClass ?>">
                <div class="nested">
                    <?php $_streetValidationClass = trim(str_replace('required-entry', '', $_streetValidationClass)); ?>
                    <?php for ($_i = 2, $_n = $this->helper('Magento\Customer\Helper\Address')->getStreetLines(); $_i <= $_n; $_i++): ?>
                        <div class="field additional">
                            <label class="label" for="street_<?php /* @escapeNotVerified */ echo $_i ?>">
                                <span><?php /* @escapeNotVerified */ echo __('Address') ?></span>
                            </label>
                            <div class="control">
                                <input type="text" name="street[]" value="<?php echo $block->escapeHtml($block->getFormData()->getStreet($_i - 1)) ?>" title="<?php /* @escapeNotVerified */ echo __('Street Address %1', $_i) ?>" id="street_<?php /* @escapeNotVerified */ echo $_i ?>" class="input-text <?php /* @escapeNotVerified */ echo $_streetValidationClass ?>">
                            </div>
                        </div>
                    <?php endfor; ?>
                </div>
            </div>
        </div>
        <div class="field">
            <div class="control">
                <input type="text" name="city" placeholder="City*" value="<?php echo $block->escapeHtml($block->getFormData()->getCity()) ?>" title="<?php /* @escapeNotVerified */ echo __('City') ?>" class="input-text <?php /* @escapeNotVerified */ echo $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('city') ?>" id="city">
            </div>
        </div>
        <div class="field">
            <div class="control">
                <select id="region_id" name="region_id"  title="<?php /* @escapeNotVerified */ echo __('State/Province') ?>" class="validate-select" style="display:none;">
                    <option value=""><?php /* @escapeNotVerified */ echo __('State*') ?></option>
                </select>
                <input type="text" id="region" name="region" value="<?php echo $block->escapeHtml($block->getRegion()) ?>" title="<?php /* @escapeNotVerified */ echo __('State/Province') ?>" class="input-text <?php /* @escapeNotVerified */ echo $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('region') ?>" style="display:none;">
            </div>
        </div>
        <div class="field">
            <div class="control">
                <input type="text" name="postcode" placeholder="Zip/Postal Code*" value="<?php echo $block->escapeHtml($block->getFormData()->getPostcode()) ?>" title="<?php /* @escapeNotVerified */ echo __('Zip/Postal Code') ?>" id="zip" class="input-text validate-zip-international <?php /* @escapeNotVerified */ echo $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('postcode') ?>">
            </div>
        </div>
        <div class="field">
            <div class="control">
                <?php echo $block->getCountryHtmlSelect() ?>
            </div>
        </div>
        <div class="field telephone">
            <div class="control">
                <input type="text" name="telephone" id="telephone" placeholder="Phone Number*" value="<?php echo $block->escapeHtml($block->getFormData()->getTelephone()) ?>" title="<?php /* @escapeNotVerified */ echo __('Phone Number') ?>" class="input-text <?php /* @escapeNotVerified */ echo $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('telephone') ?>">
            </div>
        </div>
        <div class="field ">
            <div class="control">
                <select id="secu_question" name="secu_question" required="required" title="<?php /* @escapeNotVerified */ echo __('Security Question') ?>">
                    <option value=""><?php /* @escapeNotVerified */ echo __('Please select your Security Question') ?></option>
                    <option value="What was the color of your first car" <?php if ($block->escapeHtml($block->getFormData()->getSecuQuestion())=='What was the color of your first car') {
                        echo "selected='selected'";
                    }?>><?php echo __('What was the color of your first car?') ?></option>
                    <option value="What city were you born in" <?php if ($block->escapeHtml($block->getFormData()->getSecuQuestion())=='What city were you born in') {
                        echo "selected='selected'";
                    }?>><?php echo __('What city were you born in?') ?></option>
                    <option value="What is the name of your first pet" <?php if ($block->escapeHtml($block->getFormData()->getSecuQuestion())=='What is the name of your first pet') {
                        echo "selected='selected'";
                    }?>><?php echo __('What is the name of your first pet?') ?></option>
                    <option value="What is your maternal grandmother\'s maiden name" <?php if ($block->escapeHtml($block->getFormData()->getSecuQuestion())=='What is your maternal grandmother\'s maiden name') {
                        echo "selected='selected'";
                    }?>><?php echo __('What is your maternal grandmother\'s maiden name?') ?></option>
                </select>

            </div>
        </div>
        <div class="field">
            <div class="control">
                <input type="text" name="secu_ans" id="secu_ans" placeholder="Security Answer*" value="<?php echo $block->escapeHtml($block->getFormData()->getSecuAns()) ?>" title="<?php /* @escapeNotVerified */ echo __('Security Answer') ?>" class="input-text" data-validate="{required:true}" />
            </div> 
        </div>
        <div class="field">
            <div class="control">
                <input type="checkbox" name="is_p21_customer" id="is_p21_customer" value="1" title="<?php /* @escapeNotVerified */ echo __('"I am already a Dckap customer and would like to set up a web account.') ?>" class="" /><span>I am already a Dckap customer and would like to set up a web account.</span>
            </div> 
        </div>
        <?php $addressAttributes = $block->getChildBlock('customer_form_address_user_attributes');?>
        <?php if ($addressAttributes): ?>
            <?php $addressAttributes->setEntityType('customer_address'); ?>
            <?php $addressAttributes->setFieldIdFormat('address:%1$s')->setFieldNameFormat('address[%1$s]');?>
            <?php $block->restoreSessionData($addressAttributes->getMetadataForm(), 'address');?>
            <?php echo $addressAttributes->setShowContainer(false)->toHtml()?>
        <?php endif;?>
        <input type="hidden" name="default_billing" value="1">
        <input type="hidden" name="default_shipping" value="1">
    </fieldset>
    <fieldset class="fieldset create account" data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>">
        <?php echo $block->getChildHtml('form_additional_info'); ?>
    </fieldset>
    <div class="actions-toolbar">
        <div class="primary">
            <button type="submit" class="action submit primary" title="<?php /* @escapeNotVerified */ echo __('Create an Account') ?>"><span><?php /* @escapeNotVerified */ echo __('Create an Account') ?></span></button>
        </div>
        <div class="secondary">
            <a class="action back" href="<?php echo $block->escapeUrl($block->getBackUrl()) ?>"><span><?php /* @escapeNotVerified */ echo __('Back') ?></span></a>
        </div>
    </div>
</form>
<script>
    require([
        'jquery',
        'mage/mage'
        ], function($){

            var dataForm = $('#form-validate');
            var ignore = <?php /* @escapeNotVerified */ echo $_dob->isEnabled() ? '\'input[id$="full"]\'' : 'null'; ?>;

            dataForm.mage('validation', {
                <?php if ($_dob->isEnabled()): ?>
                errorPlacement: function(error, element) {
                    if (element.prop('id').search('full') !== -1) {
                        var dobElement = $(element).parents('.customer-dob'),
                        errorClass = error.prop('class');
                        error.insertAfter(element.parent());
                        dobElement.find('.validate-custom').addClass(errorClass)
                        .after('<div class="' + errorClass + '"></div>');
                    }
                    else {
                        error.insertAfter(element);
                    }
                },
                ignore: ':hidden:not(' + ignore + ')'
            <?php else: ?>
            ignore: ignore ? ':hidden:not(' + ignore + ')' : ':hidden'
        <?php endif ?>
    }).find('input:text').attr('autocomplete', 'off');

        });
    </script>
    <?php if ($block->getShowAddressFields()): ?>
        <script type="text/x-magento-init">
            {
            "#country": {
            "regionUpdater": {
            "optionalRegionAllowed": <?php /* @escapeNotVerified */ echo($block->getConfig('general/region/display_all') ? 'true' : 'false'); ?>,
            "regionListId": "#region_id",
            "regionInputId": "#region",
            "postcodeId": "#zip",
            "form": "#form-validate",
            "regionJson": <?php /* @escapeNotVerified */ echo $this->helper('Magento\Directory\Helper\Data')->getRegionJson() ?>,
            "defaultRegion": "<?php /* @escapeNotVerified */ echo $block->getFormData()->getRegionId() ?>",
            "countriesWithOptionalZip": <?php /* @escapeNotVerified */ echo $this->helper('Magento\Directory\Helper\Data')->getCountriesWithOptionalZip(true) ?>
        }
    }
}
</script>
<?php endif; ?>
<script>
    require(['jquery'],function($){
        $(document).ready(function() {
            $('#country').find('option[value=""]').remove();

            $("#avail_credit").change(function() {
                if(this.checked) {
                    document.getElementById('fb-wrap').style.display='block';
                    $('body').css('overflow','hidden');
                }else{
                    $("#filename").empty();
                }
            });
            $('#close').on("click",function(){
                $('body').removeAttr('style','overflow');
            });
            $('.upload').on("click",function(){
                $('body').removeAttr('style','overflow');
            });

            $("select").each(function(){
                var option_val=$(this).val();
                if (option_val == '') {
                    $(this).css('color','#ccc');
                }
                else{
                    $(this).css('color','black');
                }
            });

            $('select').change(function() {
                var current = $(this).val();
                if (current != '') {
                    $(this).css('color','black');
                } else {
                    $(this).css('color','#ccc');
                }
            }); 
        });
    });
</script>
