 <?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$path = $storeManager->getStore()->getBaseUrl();
$mediaurl=$storeManager->getStore()
                    ->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);
$filesystem = $objectManager->get('Magento\Framework\Filesystem');
 $mediaDirectory = $filesystem->getDirectoryWrite(Magento\Framework\App\Filesystem\DirectoryList::MEDIA);
$mediaPath = $mediaDirectory->getAbsolutePath();

?>
 <form action="<?php echo $block->getUrl('taxexemptioncertificate/tax/taxcert');?>" method="post" enctype="multipart/form-data" data-hasrequired="<?php echo __('* Required Fields') ?>" data-mage-init='{"validation":{}}'>  
 <div id="success-alert" style="display:none" ><h3>File Uploaded Successfully</h3></div>      
 <label style>Please select state for upload Tax Exemption Certificate:</label> 
 <select name="taxcert" id="taxcert" class="state_list">
 <option value="" selected="">Please Select</option>
  <option value="California">California</option>
  <option value="Illinois">Illinois</option>
  <option value="Louisiana">Louisiana</option>
  <option value="Texas">Texas</option>
  <option value="Washington">Washington</option>
</select> 
<div style="color: #e02b27; font-size: 13px; margin-top: 5px; padding-left: 237px;" id="Selectstate-error" ></div>
<input type="hidden" id="tax_cert_url" value="<?php echo $block->getUrl('taxexemptioncertificate/tax/taxcert');?>" />




<div class="browse_file">
<p>Tax Exemption Certificate Upload:</p>
<div class="fileUpload btn btn-primary">
     <span>Choose a File</span>
    <input type="file" name="fileToUpload" id="fileToUpload" class="upload">
    </div>
<button id="upload" onclick="return validate()" style="padding: 9px 20px;font-size: 14px;">Upload</button>
<div id="fileToUpload-error" ></div>
</div>
</form>
<?php
$customer = $objectManager->get('Magento\Customer\Model\Session');
$id = $customer->getCustomer()->getId();
$resource = $objectManager->get('Magento\Framework\App\ResourceConnection');
$connection = $resource->getConnection();
$tbl = $connection->getTableName('customer_tax_exemption_certificate');
$sql = "Select * FROM $tbl where customer_id='".$id."'";
$results = $connection->fetchAll($sql); ?>
<br />
<div style="padding-bottom:20px; font-size:18px; font-weight:bold;">Uploaded Tax Exemption Certificates</div>
<table class="product_temptable" style="width:100% !important;">
<tr class="prouct-tabel"><th>State</th><th>File Name</th></tr>
<?php 
if(count($results)){ 
foreach($results as $result):?>
  <tr><td><?php echo $result['state_name'] ?></td><td><a target = "_blank" href=<?php echo $mediaurl."customer/taxcertificates/".$id."/".$result['file_name']; ?> ><?php echo $result['file_name'] ?></a></td></tr>
<?php endforeach; } else { ?>
  <tr><td>No records found.</td></tr>
  <?php } ?>
</table><script type="text/javascript">
function validate() {
          var fileToUpload = document.getElementById("fileToUpload");
          var Selectstate = document.getElementById("taxcert");
          document.getElementById("fileToUpload-error").innerHTML="";
          document.getElementById("Selectstate-error").innerHTML="";
//          if (fileToUpload.value == "" || fileToUpload.value == null) {
//             document.getElementById("fileToUpload-error").innerHTML="Please Choose a PDF File.";
//             var err1 = 1;
//          } else{
//            document.getElementById("fileToUpload-error").innerHTML="";
//            var err1 = '';
//          }
          if(Selectstate.value == "" || Selectstate.value == null) {
            document.getElementById("Selectstate-error").innerHTML="Please Select a value.";
            var err2 = 1;
          } else{
            document.getElementById("Selectstate-error").innerHTML="";
            var err2 = '';
          }  
          if( err2)   
            return false;
          else
            return true;
      }
</script> 