<?php 
//echo '<pre>';print_r($block->getData());echo '</pre>';
$isModuleEnabled = trim($block->_scopeConfig->getValue('quickorder_section/quickorder_group_general/status', \Magento\Store\Model\ScopeInterface::SCOPE_STORE));
$widget_mode = trim($block->_scopeConfig->getValue('quickorder_section/quickorder_group_general/widget_mode', \Magento\Store\Model\ScopeInterface::SCOPE_STORE));
$requestObj = $this->getRequest();
if($requestObj->getModuleName() == 'checkout' && $requestObj->getControllerName() == 'index' && $requestObj->getActionName() == 'index') {
    $isModuleEnabled = 0;
}    
$displayPopup = 'display:none;';
if($widget_mode == 1 && $block->getData('popup_mode') == 1) {
    $isModuleEnabled  = 0;
}
if($widget_mode == 1 && $block->getData('popup_mode') == 0) {
    $displayPopup = '';
}
if($widget_mode == 0 && $block->getData('popup_mode') == 0) {
    $isModuleEnabled  = 0;
}
//echo '=='.__LINE__.'==>'. $widget_mode.'==='.$block->getData('popup_mode').'<br/>';
if($isModuleEnabled) {
    $objectManager      = \Magento\Framework\App\ObjectManager::getInstance();
    $storeManager       = $objectManager->get('Magento\Store\Model\StoreManagerInterface');
    $siteBaseUrl        = $storeManager->getStore()->getBaseUrl();
    $default_no_of_rows = trim($block->_scopeConfig->getValue('quickorder_section/quickorder_group_general/default_rows', \Magento\Store\Model\ScopeInterface::SCOPE_STORE));
    if($default_no_of_rows <= 0)
        $default_no_of_rows = 1;
    $skuQuantitySeparator = trim($block->_scopeConfig->getValue('quickorder_section/quickorder_group_general/sku_quantityseparator', \Magento\Store\Model\ScopeInterface::SCOPE_STORE));
    if($skuQuantitySeparator == '')
        $skuQuantitySeparator = '|#|';
    $ac_min_chars = trim($block->_scopeConfig->getValue('quickorder_section/quickorder_group_general/qo_charslenthac', \Magento\Store\Model\ScopeInterface::SCOPE_STORE));
    if($ac_min_chars <= 0)
        $ac_min_chars = 3;    
    ?>
    <div id='quickorder-block'>
      <link rel="stylesheet" type="text/css" href="<?php echo $block->getViewFileUrl('Dckap_Quickorder::css/dckap_quickorder.css'); ?>">    
      
      <input type="hidden" name="popupmode" id="popupmode" value="<?php echo $block->getData('popup_mode'); ?>">
      <input type="hidden" name="widgetmode" id="widgetmode" value="<?php echo $widget_mode; ?>">
      <input type="hidden" name="sbu" id="sbu" value="<?php echo $siteBaseUrl; ?>">
      <input type="hidden" name="separator" id="separator" value="<?php echo $skuQuantitySeparator; ?>">
      <input type="hidden" name="ac_min_chars" id="ac_min_chars" value="<?php echo $ac_min_chars; ?>">     
      <input type="hidden" name="img_path" id="img_path" value="<?php echo $block->getViewFileUrl('Dckap_Quickorder::images/'); ?>">       
      <div id="quickorder-form" style="<?php echo $displayPopup; ?>margin: 0 auto;">
        <div id="quickorder_loader" style="position:relative;left:400px;display:none;"><img width="40" height="40" src="<?php echo $block->getViewFileUrl('Dckap_Quickorder::images/loading.gif'); ?>"></div>
        <div>
            <div id='quickorder_message_wrap' class="message message-success success" style="display: none;">
                <div id='quickorder_message' data-ui-id="messages-message-success"></div>
            </div>
            <div id='quickorder_error_wrap' class="message message-error error" style="display: none;">
                <div id='quickorder_error' data-ui-id="messages-message-error"></div>
            </div>
        </div>
        <table cellspacing="0" id="quick-order">
          <thead class="quick-order-head">
              <tr>          
                <th class="txt-pcode">Name / Product Code</th>
                <!-- <th class="pname">Product Name</th> -->
                <th class="td-qty">Qty</th>
                <th class="td-action"></th>
              </tr>
          </thead>
          <tbody cellspacing="2" class="quick-order-body">
              <?php for ($row=0; $row < $default_no_of_rows; $row++) { ?>
              <tr>
                  <td class="td-pcode">
                    <input class="txt-pcode" type="text" name="piden[]" value="" /><div class="item_loader" style="display:none;width:25px;height:25px;"><img width="25" height="25" src="<?php echo $block->getViewFileUrl('Dckap_Quickorder::images/loading.gif'); ?>"></div>
                    <input type="hidden" name="pid[]" value="" />
                  </td>
                  <td class="td-qty"><input class="txt-qty" type="text" name="qty[]" /></td>
                  <td class="td-action" >
                      <button class="btn-remove-cart button clear-row"><span><span>Clear</span></span></button>
                  </td>
              </tr>
              <?php } ?>        
              <tr id="selection-area">
                <td class="form-action-button">
                    <button class="add-all button add-item"><img src="<?php echo $block->getViewFileUrl('Dckap_Quickorder::images/add-to.png'); ?>"><span>Add Item</span></button>
                </td>
                <td class="form-action-button">    
                    <button class="add-all button remove-item"><img src="<?php echo $block->getViewFileUrl('Dckap_Quickorder::images/remove.png'); ?>"><span>Remove Item</span></button>
                </td>
                   <td class="form-action-button-last">  
                    <button class="cus-add-to-cart-button add-all-product"><img src="<?php echo $block->getViewFileUrl('Dckap_Quickorder::images/add.png'); ?>"><span>Add all to Cart</span></button>
                   </td> 
                </td>
              </tr>
          </tbody>
        </table>    
      </div>
    <script type="text/javascript" src="<?php echo $block->getViewFileUrl('Dckap_Quickorder::js/quickorder.js'); ?>"></script>
  </div>     
<?php } ?>