
<?php

//echo $block->getProductCollection()->getSize(); exit;
if ($exist = ($block->getProductCollection() && $block->getProductCollection()->getSize())): 


    $imagewidth = 100;
$imageheight = 100 ;

$title = $block->getTitle() ? __($block->getTitle()) : 'Top Selling Items'; 

$items = $block->getProductCollection()->getItems();
$showWishlist = true;
$showCompare = true;
$showCart = true;
$templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::DEFAULT_VIEW;
$description = false;

?>
<?php
$type = 'widget-product-grid';

$mode = 'grid';



?>

<div class="home-top-selling-items">
    <div class="block-title">
        <strong role="heading" aria-level="2"><h3 style="color: #e31837"><?php /* @escapeNotVerified */ echo $title; ?></h3></strong>
    </div>
    <?php if ($exist):?>
        <div class="block widget block-bestseller-products <?php /* @escapeNotVerified */ echo $mode; ?>">


            <div class="block-content">

                <div class="products-<?php /* @escapeNotVerified */ echo $mode; ?> <?php /* @escapeNotVerified */ echo $mode; ?>">
                    <ol class="product-items <?php /* @escapeNotVerified */ echo $type; ?>">
                        <?php $iterator = 1; ?>
                        <?php foreach ($items as $item):     



                        ?>


                        <?php /* @escapeNotVerified */ echo($iterator++ == 1) ? '<li class="product-item">' : '</li><li class="product-item">' ?>
                        <div class="product-item-info">
                            <a href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($item) ?>" class="product-item-photo">
                                <img src="<?php echo $block->getTopSellingimages($item); ?>" /> 

                            </a>
                            <?php 



//$caetgories = $_product->getCategoryIds();
//$cate_names = array();
//$count = count($caetgories);
//$category_name = '';
// $count_end = $count - 2;
// if($count == 1)
// {
//   $cat_details =  $block->getCategory($caetgories[0]);
//   $cate_names[] = $cat_details->getName();
//   $url = $block->getBaseUrl();
// }else
//if($count != 0 && $count > 0)
//{
//
// for($i = ($count_end) ; $i<=($count-1); $i++){
//   
//   
//   $cat_details =  $block->getCategory($caetgories[$i]);
//   $cate_names[] = $cat_details->getName();
// }
// if(!empty($cate_names))
//{
//$category_name = implode("-",$cate_names);
//}
//}


                            ?>
                            <div class="product-item-details">
                                <strong class="product-item-name">
                                    <a title="<?php echo $block->escapeHtml($item->getName()) ?>"
                                        href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($item) ?>"
                                        class="product-item-link">
                                        <?php echo $block->escapeHtml($item->getName()) ?>
                                    </a>
                                </strong>


                                <div class="star-wrapper">
                                    <?php 


                                    if ($templateType): ?>
                                    <?php echo $block->getReviewsSummaryHtml($item,"short",true) ?>
                                <?php endif; ?>
                            </div>
                            <div class="dckap-price" >
                                <?php
                                $package_details = ''; 

                                if($item->getPackageDetails() != '')
                                {
                                    $package_details = '/ '. $item->getPackageDetails();
                                }else{
                                    $package_details = '/ each';
                                }
                                echo $block->getCurrentCurrencySymbol().number_format($item->getFinalPrice(), '2', '.', ',').$package_details;
                                ?>
                            </div>

                            <div class="product-item-actions">

                                <div class="actions-primary">
                                    <?php if ($item->isSaleable()): ?>
                                        <?php if ($item->getTypeInstance()->hasRequiredOptions($item)): ?>
                                            <div class="product-add-form">
                                                <form action="<?php echo $block->getAddToCartUrl($item); ?> " method="post" id="product_addtocart_form" novalidate="novalidate">
                                                    <input type="hidden" name="product" value="<?php echo $item->getId(); ?>">
                                                    <input type="hidden" name="selected_configurable_option" value="">
                                                    <input type="hidden" name="related_product" id="related-products-field" value="">
                                                    <input name="form_key" type="hidden" value="BFtNKHCvAmjXAQ66">                            <div class="box-tocart">
                                                    <div class="fieldset">

                                                        <div class="actions">
                                                            <button type="submit" title="Add to Cart" class="action primary tocart" id="product-addtocart-button">
                                                                <span>Add to Cart</span>
                                                            </button>
                                                        </div>
                                                    </div>
                                                </form>
                                            </div>
                                        <?php else: ?>
                                            <?php
                                            $postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
                                            $postData = $postDataHelper->getPostData($block->getAddToCartUrl($item), ['product' => $item->getId()]);
                                            ?>
                                            <button class="action tocart primary"
                                            data-post='<?php /* @escapeNotVerified */ echo $postData; ?>'
                                            type="button" title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>">
                                            <span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
                                        </button>
                                    <?php endif; ?>
                                <?php else: ?>
                                    <?php if ($item->getIsSalable()): ?>
                                        <div class="stock available"><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>
                                    <?php else: ?>
                                        <div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
                                    <?php endif; ?>
                                <?php endif; ?>
                            </div>


                        </div>

                    </div>    
                </div>
                <?php echo($iterator  == count($items)+1) ? '</li>' : '' ?>
            <?php endforeach ?>
        </ol>
    </div>
</div>
</div>
</div>

<?php endif;?>
<?php endif;?>
<script>
    require([
        'jquery',
        'mage/mage',
        'Magento_Catalog/product/view/validation',
        'Magento_Catalog/js/catalog-add-to-cart'
        ], function ($) {
            'use strict';
            $('.rating-input').click(function(event){
                event.preventDefault();

            })

            $('#product_addtocart_form').mage('validation', {
                radioCheckboxClosest: '.nested',
                submitHandler: function (form) {
                    var widget = $(form).catalogAddToCart({
                        bindSubmit: false
                    });

                    widget.catalogAddToCart('submitForm', $(form));

                    return false;
                }
            });
        });
    </script>