<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$customerSession = $objectManager->get('Magento\Customer\Model\Session');
$siteBaseUrl = $storeManager->getStore()->getBaseUrl();
?>
<div class="page-title-wrapper">
    <h1 class="page-title">
        <span class="base" data-ui-id="page-title-wrapper">REQUEST FOR QUOTE</span>    </h1>
    </div>
<form class="form requestquote"
      action="<?php /* @escapeNotVerified */ echo $block->getFormAction(); ?>"
      id="requestquote_form"
      enctype="multipart/form-data"
      method="post"
      data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>"
      data-mage-init='{"validation":{}}'>
       <?php echo $block->getBlockHtml('formkey'); ?>                         
                                
    <fieldset class="fieldset">
       
        <div class="field required">
        <input type="hidden" name="sbu" id="sbu" value="<?php echo $siteBaseUrl; ?>">
        <input type="hidden" name="img_path" id="img_path" value="<?php echo $block->getViewFileUrl('Dckap_Requestquote::images/'); ?>">
        <?php if(!$customerSession->getCustomer()->getId()){
            $status = "block";
            }else{
            $status = "none";
            }
        ?>
        <ul class="request_quote" style="display:<?php echo $status; ?>">
        <li>
                <label class="label verified" for="req_name"><?php echo __('Name') ?></label>
                 <input name="req_name" id="req_name" value="" class="input-text" type="text" data-validate="{required:true}"/>
                 </li><li>
                 <label class="label" for="req_company"><?php echo __('Company') ?></label>
                 <input name="req_company" id="req_company" value="" class="input-text" type="text" />
                 </li><li>
                 <label class="label verified" for="req_company"><?php echo __('Email Address') ?></label>
                 <input name="req_email" id="req_email" value="" class="input-text" type="text" data-validate="{required:true, 'validate-email':true}" /></li>
                 <li>
                 <label class="label verified" for="req_phone"><?php echo __('Phone Number') ?></label>
                 <input name="req_phone" id="req_phone" value="" class="input-text" type="text" data-validate="{required:true}" />
                 </li>
                 <li>
            <label class="label verified" for="phone"><?php /* @escapeNotVerified */ echo __('Shipping Zip Code') ?></label>
                <input name="req_zipcode" id="req_zipcode" value="" class="input-text" type="text" data-validate="{required:true,'validate-zip-us':true}" />
            </li></ul>
                <label class="label" for="company"><?php echo __('Stock # or Keywords:') ?></label>
                <label class="label" for="contact_name" style="width: 15%;"><span><?php /* @escapeNotVerified */ echo __('QTY') ?></span></label>
                <label class="label" for="contact_name"><span><?php /* @escapeNotVerified */ echo __('Description') ?></span></label>
                <input type="hidden" name="pid[]" id="pid[]" value="">
                <input type="hidden" name="req_product[]"  value="">
                <input type="hidden" name="req_qty[]"  value="">
                <div class="control firstlevel">
                <div class="request_input">
                
                <input name="req_product[]" value="" class="input-text req_product" type="text" /><input type="hidden" name="pid[]" id="pid[]" value=""><div class="rfq_err error" ></div><div class="item_loader" style="display:none;width:25px;height:25px;"><img width="25" height="25" src="<?php echo $block->getViewFileUrl('Dckap_Requestquote::images/loading.gif'); ?>"></div></div>
                <div class="request_input req_qty_err" style="width: 12.3%; "><input name="req_qty[]"  value="" class="txt_qty req_product" type="text" /><div class="txt_qty error" ></div></div>
                <div class="request_input"><div id="description_1" class="request_input" style="width: 100%;" ></div></div>
                <button title="Delete Row" class="add_btn button clear-row parentrow" style="top:0;"></button>
                
                
            
            </div>
            <div id="addnewquoteitem"></div>
    </div>
    
    <div class="add_button"><button title="Add New Line" type="button" class="action login primary add-qitem" name="send" id="addnewline"><span>Add New Line<span class="plus"></span></span></button></div>
       
        
        <?php if($customerSession->getCustomer()->getId()){ ?>
        <div class="field" style="width:23%">
            <label class="label verified" for="phone"><span><?php /* @escapeNotVerified */ echo __('Shipping Zip Code') ?></span></label>
            <div class="control">
                <input name="req_zipcode" id="req_zipcode" value="" class="input-text" type="text" data-validate="{required:true,'validate-zip-us':true}" />
            </div>
        </div>
        <?php } ?>
    </fieldset>
    <div class="actions-toolbar">
        <div class="primary">
            <button type="button" id="qfrsubmit" title="<?php /* @escapeNotVerified */ echo __('Submit') ?>" class="action submit primary">
                <span><?php /* @escapeNotVerified */ echo __('Submit') ?></span>
            </button>
        </div>
    </div>
</form>
<script>
require(['jquery','mage/mage'],function($) {
    $(document).ready(function () {
 $( "#requestquote_form" ).on("click","#qfrsubmit", function(){
   
        $('#requestquote_form').submit();
    
});
        $('button.add-qitem').click(function(){
var description = $( "div[id^='description_']" ).last().attr('id');
if(description){
description_id = description.replace('description_',"");
var new_id = parseInt(description_id)+1;
}else{
    var new_id = 1;
}

$( "#addnewquoteitem" ).append('<div class="add_new_line">'+
                                              '<div class="request_input"><input name="req_product[]" value="" class="input-text req_product" type="text" /><input type="hidden" name="pid[]" id="pid[]" value="" ><div class="rfq_err error" ></div>'+
                                              '<div class="item_loader" style="display:none;width:25px;height:25px;"><img width="25" height="25" src="'+$('#img_path').val()+'/loading.gif"></div></div>'+'<div class="request_input" style="width: 12.3% !important;"><input name="req_qty[]"   value="" class="txt_qty req_product" type="text"  /><div class="txt_qty error" ></div></div>'+'<div class="request_input"><div id="description_'+new_id+'"></div></div>'+'<button class="add_btn button clear-row" title="Delete Row"></button>'+
                                              '</div>');
            enableAutocompleteq(jQuery('#requestquote_form'));    
            return false;
        });  

        $('#requestquote_form').on('click', 'button.clear-row', function() {
            var parentEl = $(this);            
            //parentEl.removeClass('simple').removeClass('configurable');
            //parentEl.find('input').val('');
            //parentEl.find('.pqty,.txt-sku').text(''); //.txt-sku,.pname,
            //parentEl.find('.txt_qty').show();
            parentEl.parent('.add_new_line').remove();
            return false;
        });

        $('#requestquote_form').on('click', '.parentrow', function() {
            var parentEl = $(this);            
            //parentEl.removeClass('simple').removeClass('configurable');
            //parentEl.find('input').val('');
            //parentEl.find('.pqty,.txt-sku').text(''); //.txt-sku,.pname,
            //parentEl.find('.txt_qty').show();
            parentEl.parent('.firstlevel').remove();
            return false;
        });        


        $('.form.requestquote').on('submit', function(event) {
                        
            var count=0;
            var count1=0;
            var flag=false;
            var flag1=false;
                        
              $('.input-text.req_product').each(function() {
                count++;
               
                if (this.value == 0 || this.value == '') {
                   $(this).next().next('.rfq_err').html("This is a required field.");
                  flag=true;
               }else{
                 $(this).next().next('.rfq_err').html('');
               }
              });
              $('.txt_qty.req_product').each(function() {
                count1++;
                
                if (this.value == '') {
                  $(this).next('.txt_qty').html("This is a required field.");
                  flag=true;
                }else if(!$.isNumeric(this.value) || this.value<=0){
                    $(this).next('.txt_qty').html('Please enter the valid Qty.');
                  flag=true;
                }
                else{
                 $(this).next('.txt_qty').html('');
               }
              });
              
            if (flag1 || flag) {
              return false;
            }                         

        });    
    });
 });
function enableAutocompleteq(pSelector) {  
    var cache = {};
    jQuery('#requestquote_form').find('input[name="req_product[]"]').autocomplete({
        minLength : 4,
        delay:500,
        html: true,        
        source: function (request, response) {
            var searchKeyword = request.term;
            //alert(searchKeyword);
            if(jQuery.trim(searchKeyword) != '') {
                if ( searchKeyword in cache ) {
                    response(cache[searchKeyword]);
                    return;
                }
                var ac_item = this.element;
                ac_item.siblings('.item_loader').show(function(){
                    jQuery.ajax({
                        cache:true,
                        dataType:'json',
                        method: 'POST',
                        /*async: false,*/
                        url:jQuery('#sbu').val()+'quickorder/index/quote',
                        data:{query:searchKeyword},
                        crossDomain:false,
                        success:function(datasuggestions){
                            /*if(jQuery.trim(datasuggestions) == '') {
                                datasuggestions = [{"label":"No Matches Found","title":"No Matches Found","value":"no-matches"}];
                            }*/
                            cache[searchKeyword] = datasuggestions;
                            response(datasuggestions);  
                            ac_item.siblings('.item_loader').hide();  
                        }
                    });
                });

            }                              
        },
        
        select: function( event, ui ) {
            if(ui.item.value == 'no-matches')
                return false;
            var ac_element = jQuery(this);
            ac_element.siblings('.item_loader').show();            
            var elmParent = jQuery(this).parents('div');
            //var parentTd = jQuery(this).parents('td');
            //var parentTd = jQuery(this).parents('td');
            //jQuery('#quickorder_message_wrap,#quickorder_error_wrap').hide();
            var prodId = ui.item.value;
            var itemTitle = jQuery('<textarea />').html(ui.item.label).text();
            jQuery(this).val(itemTitle);
            jQuery(this).siblings('input:hidden').val( ui.item.value );            
            //elmParent.find('.txt-sku').html(ui.item.sku);
            //elmParent.find('.pqty').html(ui.item.price);
            //elmParent.find('.txt_qty').val(1);
            //ac_element.parent('#pdescriptionf').text(ui.item.pdesc);
            console.log(jQuery(this).parent().parent().find( "div[id^='description_']" ))
            jQuery(this).parent().parent().find( "div[id^='description_']" ).html(ui.item.label);
            //parentTd.find('.confBlock').remove();
            if(jQuery.trim(ui.item.ptype) == 'configurable' && (ui.item.value*1) > 0) {                                
                elmParent.removeClass('simple').addClass('configurable');
                elmParent.find('.txt-qty').hide();
                elmParent.find('.pqty').html('');
                var $confBlock = jQuery("<div>",{ class:'confBlock'});                                
                //parentTd.append($confBlock);   
                jQuery.ajax({
                    cache:true,
                    method: 'POST',
                    url:jQuery('#sbu').val()+"quickorder/index/getproductinfo",
                    data:{ptype:jQuery.trim(ui.item.ptype),pid:ui.item.value},
                    crossDomain:false,
                    success:function(confResponse){
                        if(confResponse != '') {
                            var cresults = jQuery.parseJSON(confResponse);
                            if(jQuery.trim(cresults.status) == 'success') {
                                var confOptions = optionwidth = optionMargin = '';                            
                                var attCounter = 0;
                                var attIds = new Array();
                                jQuery.each(cresults.cdata.data, function (cindex,cvalue) {
                                    attCounter++;
                                    var attParts = cindex.split('_');
                                    attIds[attCounter] = attParts[1]+'$$$'+cvalue.attrLabel+'$$$'+attParts[0];
                                    if(jQuery.trim(attParts[0]) == 'size') {
                                        optionwidth = '100px';optionMargin = 'margin-left:10px;';
                                    }
                                    else {
                                        optionwidth = '125px';optionMargin = '';
                                    }
                                    var $selectBox = jQuery("<select>",{ id:cindex+'_'+ui.item.value, title: jQuery.trim(attParts[0]), class:'confAttr_'+attCounter, name: jQuery.trim(attParts[0])+'[]', style: optionMargin+'width:'+optionwidth+';'});                                
                                    $confBlock.append($selectBox);
                                    jQuery.each(cvalue, function (oid,ovalue) {
                                        if(jQuery.trim(oid) != 'attrLabel') {
                                            var $coption = jQuery("<option>",{value:oid});
                                            $coption.html(ovalue);
                                            $selectBox.append($coption);    
                                        }                                                                       
                                    });
                                });                                
                                var $cProduct       = jQuery("<input>" , { type: 'hidden', id:'confProd' , name:'confProd[]' });
                                $confBlock.append($cProduct);                                
                                var $cquantityBox   = jQuery("<input>" , { type: 'text', id:'confQty' , value:'1', title: 'quantity', class:'confQtyClass', style:'margin-left:10px;width:50px;' });
                                $cProduct.after($cquantityBox);                                
                                var $cAddToListBtn = jQuery("<input>" , { type: 'button', title: 'Add to list', id:'confAddtoList', value:'+', class:'confAddtoListClass'});
                                $cquantityBox.after($cAddToListBtn);
                                $confBlock.find("select[class='confAttr_1']").change(function(){
                                    $confBlock.find("select[class^='confAttr_']:not(select.confAttr_1)").each(function(){
                                        jQuery(this).find('option:eq(0)').prop('selected','true');
                                    });    
                                });                                
                                var $selectedConfProductsBlock = jQuery('<div>',{ id:'confProdBlock' , name:'confProdBlock[]' }); 
                                $cAddToListBtn.after($selectedConfProductsBlock);
                                $cAddToListBtn.click(function(){                                    
                                    var $selectedConfProduct = jQuery('<span>'); //,{ style:'margin-left:10px;margin-top:10px;' }
                                    $selectedConfProductsBlock.append($selectedConfProduct); //.append('<br/>')
                                    var mappingKeyParts = new Array();
                                    var priceMappingKeyParts = new Array();
                                    var super_attribute = attInfo = '';
                                    for (var attIndex = 1; attIndex <= attCounter; attIndex++) {
                                        attInfo = attIds[attIndex].split('$$$');
                                        attrField = jQuery(this).siblings('select.confAttr_'+attIndex);
                                        $selectedConfProduct.append("<strong>"+attInfo[1]+" : </strong>"+attrField.find('option:selected').text()+'&nbsp;&nbsp;');
                                        mappingKeyParts.push(attInfo[0]+'='+attrField.val());
                                        priceMappingKeyParts.push(attInfo[2]+'_'+attrField.val());
                                    }
                                    $selectedConfProduct.append("<strong>Qty : </strong>"+attrField.siblings('.confQtyClass').val()+'&nbsp;&nbsp;');                                    
                                    super_attribute = mappingKeyParts.join(',');
                                    var $superAttributeData = jQuery('<input>',{ value: super_attribute , id:'confAttrData', type:'hidden' , name:'confAttrData[]'});
                                    $selectedConfProduct.append($superAttributeData);
                                    var $simpleProdQty = jQuery('<input>',{ value:  $cquantityBox.val(), id:'confAttrQty', type:'hidden' , name:'confAttrQty[]'});
                                    $selectedConfProduct.append($simpleProdQty);                                    
                                    prodPriceKey = priceMappingKeyParts.join('-');
                                    jQuery.each(cresults.cdata.mapping, function (mindex,mvalues) {
                                        if(mindex == prodPriceKey) {
                                            $selectedConfProduct.append("<strong>Price : </strong>"+mvalues.price+'&nbsp;&nbsp;');
                                            return false;
                                        }
                                    });
                                    var $deleteConfProduct = jQuery('<img>',{ class: 'deleteConfProduct', title: 'Delete', src: jQuery('#img_path').val()+'/delete.png' , width:16, height:16});
                                    $selectedConfProduct.append($deleteConfProduct);    
                                });
                                ac_element.siblings('.item_loader').hide();
                            }   
                        }
                    }
                });                
            } else {
                elmParent.removeClass('configurable').addClass('simple');
                elmParent.find('.txt-qty').show();
                ac_element.siblings('.item_loader').hide();
            }
            return false;
        }/*,
        messages: {
            noResults: '',
            results: function() {}
        }*/
    }).click(function(){
            jQuery(this).autocomplete('search');        
    });  
    return false;
}

</script>