
<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$customerSession = $objectManager->get('Magento\Customer\Model\Session');
//$_scopeConfig = $objectManager->get('\Magento\Framework\App\Config\ScopeConfigInterface');
?>

<script type="text/javascript">
  function toggle_visibility(id) 

  {
    var element = document.getElementById(id);
    if (element.style.display == 'block' || element.style.display=='')
    {
      element.style.display = 'none';
    }
    else 
    {
      element.style.display = 'block';
    }
  }
</script>
<nav class="dckap-menu">
  <ul>
    <li><a href="<?php echo $block->getUrl('location');?>"><i class="loc-ico dckap-sprite"></i><h3>Locations</h3></a></li> 
    <li><a href="<?php echo $block->getUrl('contact-us');?>" ><i class="contact-ico dckap-sprite"></i><h3>Contact Us</h3></a></li>   
    <li><a href="<?php echo $block->getUrl('about-us');?>" ><i class="about-ico dckap-sprite"></i><h3>About Us</h3></a></li> 
    <li><a href="<?php echo $block->getUrl('resource-hub');?>" ><i class="resource-ico dckap-sprite"></i><h3>Resource Hub</h3></a></li>
    <li><a href="<?php echo $this->getBaseUrl().'requestquote/index/index/' ?>"><i class="req_ico dckap-sprite"></i><h3>Request Quote</h3></a></li> 
    <li><a href="javascript:void(0);" class="popup-head" data-flag="quickorder-form" onclick="toggle_visibility('quickorder-form')" id="q-order"><i class="ouick-ico dckap-sprite"></i><h3>Quick Order</h3></a>
      <?php 
      $default_no_of_rows = trim($block->_scopeConfig->getValue('quickorder_section/quickorder_group_general/default_rows', \Magento\Store\Model\ScopeInterface::SCOPE_STORE));
      if($default_no_of_rows <= 0)
        $default_no_of_rows = 1;
      $siteBaseUrl        = $storeManager->getStore()->getBaseUrl();
      $ac_min_chars = trim($block->_scopeConfig->getValue('quickorder_section/quickorder_group_general/qo_charslenthac', \Magento\Store\Model\ScopeInterface::SCOPE_STORE));
      if($ac_min_chars <= 0)
        $ac_min_chars = 3;
      ?>
      <div id='quickorder-block' >
        <link rel="stylesheet" type="text/css" href="<?php echo $block->getViewFileUrl('Dckap_Quickorder::css/dckap_quickorder.css'); ?>">   
        <input type="hidden" name="sbu" id="sbu" value="<?php echo $siteBaseUrl; ?>">
        <input type="hidden" name="ac_min_chars" id="ac_min_chars" value="<?php echo $ac_min_chars; ?>">     
        <input type="hidden" name="img_path" id="img_path" value="<?php echo $block->getViewFileUrl('Dckap_Quickorder::images/'); ?>">    
        <div id="quickorder-form" style="margin: 0 auto; display:none " class="popup-flag">
          <div id="quickorder_loader" style="position:relative;left:400px;display:none;"><img width="40" height="40" src="<?php echo $block->getViewFileUrl('Dckap_Quickorder::images/loading.gif'); ?>"></div>
          <div>
            <div id='quickorder_message_wrap' class="message message-success success" style="display: none;">
              <div id='quickorder_message' data-ui-id="messages-message-success"></div>
            </div>
            <div id='quickorder_error_wrap' class="message message-error error" style="display: none;">
              <div id='quickorder_error' data-ui-id="messages-message-error"></div>
            </div>
          </div>
          <table cellspacing="0" id="quick-order">
            <thead class="quick-order-head">
              <tr>          
                <th class="txt-pcode">Name / Product Code</th>
                <!-- <th class="pname">Product Name</th> -->
                <th class="td-qty">Qty</th>
                <th id="close-q" class="td-action">x</th>
              </tr>
            </thead>
            <tbody cellspacing="2" class="quick-order-body">
              <?php for ($row=0; $row < $default_no_of_rows; $row++) { ?>
              <tr>
                <td class="td-pcode">
                  <input class="txt-pcode" type="text" name="piden[]" value="" /><div class="item_loader" style="display:none;width:25px;height:25px;"><img width="25" height="25" src="<?php echo $block->getViewFileUrl('Dckap_Quickorder::images/loading.gif'); ?>"></div>
                  <input type="hidden" name="pid[]" value="" />
                </td>
                <td class="td-qty"><input class="txt-qty" type="text" name="qty[]"  /></td>
                <td class="td-action" >
                  <button title="Clear" class="btn-remove-cart button clear-row"><span><span>Clear</span></span></button>
                </td>
              </tr>
              <?php } ?>        
              <tr id="selection-area">
                <td class="form-action-button" style="width:115px;text-align: left;padding: 10px 0 10px 10px;">
                  <button title="Add Item" class="add-all button add-item"><img src="<?php echo $block->getViewFileUrl('Dckap_Quickorder::images/add.png'); ?>"><span>Add Item</span></button>
                </td>
                <td class="form-action-button" style="width:140px;text-align: center">    
                  <button title="Remove Item" class="add-all button remove-item"><img src="<?php echo $block->getViewFileUrl('Dckap_Quickorder::images/remove.png'); ?>"><span>Remove Item</span></button>
                </td>
                <td class="form-action-button-last" style="width:150px;text-align: right">  
                  <button title="Add all to Cart" class="cus-add-to-cart-button add-all-product"><img src="<?php echo $block->getViewFileUrl('Dckap_Quickorder::images/add-to.png'); ?>"><span>Add all to Cart</span></button>
                </td> 
              </td>
            </tr>
          </tbody>
        </table>    
      </div>
    </div>     
  </li>
  <script type="text/javascript" src="<?php echo $block->getViewFileUrl('Dckap_Quickorder::js/quickorder.js'); ?>"></script>
  <script type="text/javascript" src="<?php echo $block->getViewFileUrl('Dckap_Quickorder::js/jquery.ui.autocomplete.html.js'); ?>"></script>

  <?php
  if($customerSession->isLoggedIn()) {
    ?>


    <li><a href="<?php echo $storeManager->getStore()->getBaseUrl().'customer/account/'; ?>" ><i class="accou-ico dckap-sprite"></i><h3>My Account</h3></a></li>
    <?php
  }else
  {
    ?>
    <li>
      <a href="javascript:void(0);" class="popup-head"  data-flag="order-search-form" onclick="toggle_visibility('order-search-form')" id="order-search" ><i class="order-ico dckap-sprite"></i><h3>Order Status</h3></a>
      <form action="<?php echo $block->getUrl('ordersearch/status/view');?>" method="POST" class="popup-flag" id="order-search-form" style="display:none;" data-mage-init='{"validation": {}}'>
        <div class="order-status-pop ">

          <div class="order-status-wrapper">

            <input type="text" name="sch_order_num" class="input-text" placeholder="Web Order Number *" class="ostatus" data-validate="{required:true}"/>
            <input type="text" name="sch_email_address" placeholder="Email Address *" class="ostatus" data-validate="{required:true, 'validate-email':true}"/>
            <input type="text" name="sch_zipcode" placeholder="ZIP *" class="ostatus required-entry validate-zip-international" data-validate="{required:true}"/>
            <input value="desktop" name="desktop" type="hidden">
            <div class="order-help-info"><p>If you don't have this information please </p><a href="mailto:infoindia@dckap.com" >Email Us.</a></div>
            <div class="order-status-but-bg"><button type="submit" id="search_button" class="ostatus-butt">Submit</button>
              <button type="button" id="order-search-cancel" class="ostatus-butt">Cancel</button></div>

              <!--<input type="submit" class="ostatus-butt" value="Submit"/>-->
            </div>
          </div>    
        </form>
        <script type="text/javascript">

          require(['jquery','mage/mage'], function($){

            $('#order-search-cancel').click(function() {
              $('#order-search-form').hide();

            });


            $("#search_button").click(function() {


              var itemForm = $('#order-search-form');
              itemForm.mage('validation', {});

              $("#order-search-form").attr("action", "<?php echo $block->getUrl('ordersearch/status/view');?>");

            });


          });
        </script>
      </li>
      <?php
    }
    ?>

  </ul>

</nav>

<script type="text/javascript">

  require(['jquery'], function(jQuery){
    jQuery(document).ready(function () {
      jQuery( ".popup-head" ).on('click',function() {
        jQuery('.dckap-jmenu').hide();
        var current_popup = jQuery(this).attr('data-flag');
        jQuery( ".popup-flag" ).each(function( index ) {
          if(current_popup != jQuery(this).attr('id'))
          {
            jQuery(this).hide();
          }
        });
      });
    });
  });

  require(['jquery'], function($){

    $('#close-q').click(function()
    {

      $("#quickorder-form").attr('style','display:none');
    });

    $(document).mouseup(function (e)
    {
      var container = $("#quickorder-form");
      var container2 = $(".ui-autocomplete.ui-front.ui-menu.ui-widget.ui-widget-content.shopping-list");
      var element = $("#quickorder-form").find(".ac_quickorder");
      var container1 = $("#order-search-form");

      if (!container.is(e.target) && container.has(e.target).length === 0 && !container2.is(e.target) && container2.has(e.target).length === 0)
      {
        $("#quickorder-form").attr('style','display:none');
      }
      if (!container1.is(e.target) && container1.has(e.target).length === 0)
      {
        $("#order-search-form").attr('style','display:none');
      }
    });

  });
</script>